version: "3.4"
services:
    api:
        image: "dhimas12/hannsoftwareapi:latest"
        ports:
          - "5001:80"
        depends_on:
          - db
        environment: 
          ASPNETCORE_ENVIRONMENT: Development

    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
          - "1433:1433"

        environment:
            MSSQL_SA_PASSWORD: "Testexec123"
            ACCEPT_EULA: "Y"